### ISSUE TITLE
What should this GitHubs project's structure look like?

### ISSUE THREAD

**Issue by MMenninger** [CMAP-REPOS/cmapplot#1]

**Comment by nmpeterson** [comment]
A simpler version of [`easystats/see`](https://easystats.github.io/see/) is probably a good target to start with, if we are limiting this to color palettes and chart/map themes.

**Comment by nmpeterson** [comment]
Here's a good reference for all of the ggplot parameters we can modify: https://ggplot2.tidyverse.org/reference/theme.html

**Comment by tallishmatt** [comment]
Marking this as done, as I think we're on the same page at this point.
