### ISSUE TITLE
automatically highlight final data point on a time series chart with dot and data label

### ISSUE THREAD

**Issue by matthewstern** [CMAP-REPOS/cmapplot#10]
see e.g. Noel's ACS indicator R script and [this graph](https://www.cmap.illinois.gov/2050/indicators/workforce-participation#InclusiveGrowth).

**Comment by nmpeterson** [comment]
The labeling part of this is done as of #22. Labels can be added via `+ geom_text_lastonly()`.

Better font handling and an option for adding points still to come.

**Comment by nmpeterson** [comment]
This seems apropos to all of the font work: https://stackoverflow.com/questions/48977963/how-to-let-geom-text-inherit-theme-specifications-ggplot2

**Comment by nmpeterson** [comment]
I am going to consider this a sub-issue to #24 and close it.
