### ISSUE TITLE
Add title to vertical chart layout

### ISSUE THREAD

**Issue by dlcomeaux** [CMAP-REPOS/cmapplot#113]
Building on the work done in #111 and functionality tested in #109 , I am going to work on adding titles to the vertical layout.

**Comment by matthewstern** [comment]
@dlcomeaux, concurrently with this work I'd like to overhaul the finalize vignette. 

I propose rearranging the sections as follows, and making substantive changes as per the parentheticals:

- Basic implementation
   - Finalizing
   - Exporting
- Customization
   - Top-level position adjustments *(remove debug mode, remove reference to `legend_shift`)*
   - Exporting a graph with no title
   - Title and caption formatting
- Advanced customization
   - Using debug mode
   - Overriding plot constants
   - Shifting the legend *(new, brief section explaining `legend_shift`)*
   - Many, many margins *(consider adding second slide to describe margins in a `title_width = 0` setting)*

What do you think? I'm happy to work on this concurrently/after your commits.

**Comment by dlcomeaux** [comment]
That sounds like a good structure to me, @matthewstern
