### ISSUE TITLE
update example

### ISSUE THREAD

**Issue by matthewstern** [CMAP-REPOS/cmapplot#118]
One of the examples in finalize_plot refers to the argument `title_width`. This should be updated to `sidebar_width` and a quick scan of examples in other man files should be done to confirm no deprecated args or constants are used.

**Comment by dlcomeaux** [comment]
I didn't find any in the actual finalize vignette, but there are a few in the cookbook. I'm going to update those, plus add in some updates to the recessions section, as part of the v1.2 effort.

**Comment by matthewstern** [comment]
Thanks @dlcomeaux! I'm actually talking about the [man file](https://cmap-repos.github.io/cmapplot/reference/finalize_plot.html). I for one have not looked at super closely at any of the man files in quite some time. 

If revisiting man files, it may also be worthwhile to think about the example code in the context of what is rendered on the pkgdown site. For example, simplifying example sections like [this one](https://cmap-repos.github.io/cmapplot/reference/geom_recessions.html) so that it contains just a few examples that demonstrate the range of functionality a function offers.

**Comment by dlcomeaux** [comment]
@matthewstern ok, I've made a few tweaks accordingly. On the question of the man files, I guess I think it still makes sense to have a more detailed documentation version in the man file for the function specifically - it can go into the more technical details that someone reviewing the vignette on `finalize` is less likely to need?

**Comment by matthewstern** [comment]
yes, definitely. Not saying we should avoid technical details. Just that we should recognize that the results of examples are displayed on the website and make sure our examples tell the important stories both in code and output.

In truth, this comment may in part be a response to how many of our font-based examples are set to not run due to their breaking `devtools::check()`. There's a chance that if we update to systemfonts that will change, and we can revisit man pages like [this one](https://cmap-repos.github.io/cmapplot/reference/cmap_default_aes.html) that don't show any outputs at all.

**Comment by dlcomeaux** [comment]
Oh I see your point. My bias would be to wait to do that, at least until we have a conversation as a group about whether and to what degree we want to restructure (since that would take a bit of work, and might involve rework if/when we fix the fonts).
