### ISSUE TITLE
unable to use cmapplot continuous color palettes for fill aesthetic

### ISSUE THREAD

**Issue by tkoyejo** [CMAP-REPOS/cmapplot#119]
I wanted to apply the built-in CMAP continuous palette to produce a continuous gradient fill aesthetic in a stacked bar chart. When I apply `cmap_fill_continuous(palette = "seq_blues")` to a stacked bar chart, I get the following error: "Error: Discrete value supplied to continuous scale". If I switch to `cmap_color_continuous(palette = "seq_red_purple")`, the code is ignored and the default ggplot colors are used.

I ended up having to use the ggplot color brewer, which worked. The example output I seek is attached. 
`scale_fill_brewer(palette = "Blues")` 

![figure17_title](https://user-images.githubusercontent.com/22479581/109708527-2227a600-7b61-11eb-8bde-bbdc23be7660.png)

**Comment by matthewstern** [comment]
@gritzenthaler, this is a bit of a different color application than we had originally scoped and tested. Is this code modifiable to enable the application of a continuous palette to a discrete set of categories?

**Comment by gritzenthaler** [comment]
Yes I believe we talked about this sort of application a while ago, particularly in regards to choropleth maps. I'm sure it's possible, so I'll look into it once I have some time in the coming week.

**Comment by matthewstern** [comment]
Is this the same issue as #70?

**Comment by tkoyejo** [comment]
If I'm reading this right, sounds like the same issue to me.

**Comment by matthewstern** [comment]
@gritzenthaler for the time being I've assigned you to both issues and added both to the v1.2 milestone. Feel free to close one or the other if you determine them to be duplicates.
