### ISSUE TITLE
built outputter function

### ISSUE THREAD

**Issue by matthewstern** [CMAP-REPOS/cmapplot#12]
export WEB, POWERPOINT, and REPORT versions of graphics as per the DESIGNER GUIDELINES section of [this guide](https://cmapil.sharepoint.com/resources/communications/Shared%20Documents/Communications%20Resources%202019/Other%20Resources/COMMS_Visuals_Best_Practices_FEB2020.pdf)

Presumably based on bbplot::finalise_plot

**Comment by nmpeterson** [comment]
Just a note: everything should be exported in SVG format for Comms, as that is easiest for them to edit in Illustrator.

**Comment by tallishmatt** [comment]
do we want the ability to export in jpg and pdf as well, for more immediate uses that don't involve further tweaking by comms?

**Comment by nmpeterson** [comment]
I imagine this would be useful, although PNG (or GIF) should be used instead of JPG, which is good for photos but not graphics. I think an `output_format` parameter for the function, with a default of `"svg"` would be a good way to implement this, so that if not explicitly specified then an SVG will be exported.

**Comment by tallishmatt** [comment]
Once we get the font situation figured out, it would be cool if this function issued a warning if the correct fonts were not being used.

**Comment by tallishmatt** [comment]
@sarahcmap, not sure this was 100% clear from our meeting yesterday: In terms of final chart layout, our direction at this point is to combine the "designer guidelines" from the [link](https://cmapil.sharepoint.com/resources/communications/Shared%20Documents/Communications%20Resources%202019/Other%20Resources/CMAP_Visuals_Best_Practices_comms_use.pdf) in the first post of this issue with a graphic from a recent policy update, for example [here](https://www.cmap.illinois.gov/updates/all/-/asset_publisher/UIMfSLnFfMB6/content/chicago-region-attracting-but-not-retaining-working-age-adults). The current model has the title, source, and note on the left and the legend above. Nancy will supposedly be updating the designer guidelines soon with the new design, but if that doesn't come down the pipe soon it's probably worth going to chat with her.

Also, where do we want to go with the larger question of what goes in `theme_cmap` and what goes in `finalize_plot`? It seems like some aspects are really clearly in this project (e.g. file format, dimensions, etc) but things like font size, legend placement, etc are maybe undetermined at this point. Might be worth sitting down with @MMenninger before going too deep?

**Comment by sarahcmap** [comment]
Thanks for the additional details Matt - I'm still just getting started but I'll touch base with Martin/Nancy as needed!

**Comment by nmpeterson** [comment]
Be forewarned that if we add a PDF-exporting option, we will probably run into issues with the fonts. See [this StackOverflow Q&A](https://stackoverflow.com/questions/46008304/saving-ggplot-graph-to-pdf-with-fonts-embedded-in-r/46532114#46532114) for more info.

**Comment by matthewstern** [comment]
- [ ] Width of sidebar as argument – percentage?
- [ ] Auto-breaking title and note/source text (in progress)
- [ ] Letting of title and note/source text (awaiting details from Nancy)
- [ ] Strong (2 point) horizontal line across top (in progress)
- [ ] Four output options (based on best practices document): 
    - [ ] Default = Indesign (note: font sizes inherited from theme)
    - [ ] Web = Web
    - [ ] Report = Word
    - [ ] Presentation = Powerpoint
- [ ] Multiple output modes:
    - [ ] View in R (use Window function so width is specified?)
    - [ ] SVG
    - [ ] PNG
    - [ ] PDF (note font challenges, see Noel's comment above)

**Comment by matthewstern** [comment]
Specs from Nancy:

graph area
- [ ] Space for graph title/note/source: 2.1503 in
- [ ] Space between the title and graph: 0.16 in
- [ ] Graph: 6.921 in

other
- [ ] line on top of title/graph: .0277 in
- [ ] leading for Title: 19pt
- [ ] leading for Note/Source: 13.2pt

**Comment by matthewstern** [comment]
some links on grob management for safe keeping:
# https://cran.r-project.org/web/packages/gridExtra/vignettes/arrangeGrob.html
# https://stackoverflow.com/questions/59012782/ggplot2-how-to-align-grobs-to-sides-using-arrangegrob
# https://genviz.org/module-07-appendix/0007/01/01/advancedggplot2/
