### ISSUE TITLE
Allow capitalized race designations for cmap_[fill/color]_race

### ISSUE THREAD

**Issue by dlcomeaux** [CMAP-REPOS/cmapplot#121]
Right now, the `cmap_fill_race` and `cmap_color_race` will only work if your race/ethnicity designations are in lower case. I propose that we also enable it to work in the case when they are the same words but in different cases, to make it easier to generate production-ready graphics. I can look into this, I don't imagine it will be terribly complicated.

**Comment by nmpeterson** [comment]
I don't follow. The parameter names are lowercase, yes, but the supplied values can be anything. For example, the [final cookbook chart](https://cmap-repos.github.io/cmapplot/articles/cookbook.html#race-and-ethnicity-time-series-line-graph-1) includes this code:

```
  cmap_color_race(white = "White (non-Hispanic)",
                  black = "Black",
                  hispanic = "Hispanic",
                  asian = "Asian",
                  other = "All")
```

Am I misunderstanding the issue?

**Comment by dlcomeaux** [comment]
My suggestion is that, in that case, you wouldn't need to specify - we could put in some code so that "white" or "White" or "WHITE" would all default to using the value for "white" (unless otherwise specified). My thinking here is that, since we tend to publish things that are not all in lower case, this could save a bit of time. It is by no means a critical improvement.

**Comment by nmpeterson** [comment]
Looping @gritzenthaler in, as she understands the current behavior best.

**Comment by gritzenthaler** [comment]
Sorry I'm late to the party. I think it would involve some regex work but you're right, it would only save us an inconsequential amount of time from inputting the parameter names. They show up on the graph as they appear in your data, or they can be edited with some legend customizing code.

**Comment by matthewstern** [comment]
@gritzenthaler what do you think about coding in a single default set of values into the function, so that if most likely/preferred text was coded into the data, the user would not have to type in values manually? (Am I correct in understanding that right now no default values are set?)

**Comment by dlcomeaux** [comment]
@matthewstern right now the default values are the lower case race/ethnicity (i.e., "white").

**Comment by nmpeterson** [comment]
To change the defaults, I think it would have to be done in `/R/colors_discrete.R` where `cmap_palettes$race` is defined.
