### ISSUE TITLE
deactivate top line

### ISSUE THREAD

**Issue by ygalanak** [CMAP-REPOS/cmapplot#144]
Is there a way to deactivate the top line above the title and graph?

**Comment by dlcomeaux** [comment]
Hi! We haven't built that as functionality, but we could potentially do it. There are some underlying mechanics that might require some work to do it - it's not necessarily a quick fix. I'll add it to the list of ideas for potential improvement. Thanks for the suggestion.

**Comment by dlcomeaux** [comment]
@ygalanak I have an easier than expected solution. You can remove the top line with the existing function by adding `overrides = list(lwd_topline = 0)` to the `finalize_plot()` function. You can then also remove any additional margins by setting `margin_topline_t = 0)` and/or `margin_legend_t = 0` in the same `list()` value, if desired.
