### ISSUE TITLE
Address deprecation of save-state and set-output

### ISSUE THREAD

**Issue by dlcomeaux** [CMAP-REPOS/cmapplot#146]
In the most recent pkgdown and system checks, I noticed a flag that the GitHub actions we have in this package rely on a [deprecated ](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)code. Specifically, it says:

"Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/"

This is happening in the `Cache R packages` section of the pkgdown file, [here](https://github.com/CMAP-REPOS/cmapplot/blob/75b6eab0ada1c6cb65128ac494f5a9a2eb414f94/.github/workflows/pkgdown.yaml#L49) . It also appears to have the same problem on the other two checks that are coming out of the `check-standard.yaml` file.

I'm not sure exactly how to address this - it might involve the hashed system keys? @EthanJantz @amcadamsCMAP @leotorres114  would welcome any thoughts here.

**Comment by dlcomeaux** [comment]
Note - the issue will come to a head on May 31st, and the code will trigger an error after June 1st (we think).

**Comment by EthanJantz** [comment]
As you noted, this looks like it happens in `actions/cachev2`, and it looks like this was fixed as of v3: https://github.com/actions/cache/commit/5868318cdc157d6779e30bbb640f004e827f943d

I created a branch to fix this. I'll take a stab at it when I find some time!
