### ISSUE TITLE
Appreciation post

### ISSUE THREAD

**Issue by JDenn0514** [CMAP-REPOS/cmapplot#160]
Hi! I don't have any issues but just wanted to thank you all.

I happened to stumble upon this package when I was trying to figure out how to use `systemfonts` to load custom fonts in my own R package, [adlgraphs](https://jdenn0514.github.io/adlgraphs/dev/index.html). I was trying to switch from using `sysfonts` to `systemfonts` in my `.onLoad()` but my pkgdown site kept failing as it was not able to load the fonts properly (or at least I think that's why). 

Not knowing what else to do, I went onto Github and put in ".onLoad(...) {systemfonts" to just see if anyone was using it and how they were. That's when I found this package. I took some of the code in `cmapplot_globals.R` and the code in `.onLoad()` from `cmapplot.R` and modified it for my own package. Now my package loads properly and everything! 

So thank you again!

**Comment by MMenninger** [comment]
Glad the code was helpful. We are a government agency - so we try to post useful code for others.
