### ISSUE TITLE
improved x axis control in TS

### ISSUE THREAD

**Issue by matthewstern** [CMAP-REPOS/cmapplot#26]
In time series, x labels should be integers. Also, in some situations we have published graphs where the first year is full ("2001") and those that follow are partial ('02, '03, '04, etc). We could make this an easy add (I've already found a source for the first half).

**Comment by matthewstern** [comment]
Re establishing partial breaks, `scale_*_date()` and `scale_*_continuous()` in ggplot2 have arguments for `labels`, which according to their documentation can take a function that inputs the axes' breaks and returns a string of labels. It should be relatively easy to program a function that abbreviates certain dates. I would recommend that any function we program takes an argument that specifies which dates to not abbreviate. For example:

```
labels = abbreviate_dates(full_by_pos = c(1,8)) # don't abbreviate date 1 or 8
labels = abbreviate_dates(full_by_date = c(2000, 2010)) # don't abbreviate 2000 or 2010
```

**Comment by dlcomeaux** [comment]
I found some code ([here](https://joshuacook.netlify.app/post/integer-values-ggplot-axis/)) that accomplishes the first and I'll take a crack at the second.

**Comment by matthewstern** [comment]
@dlcomeaux  note that [this half-baked function](https://cmap-repos.github.io/cmapplot/reference/integer_breaks.html) has been a part of cmapplot for forever. It can be built upon or dumped if better tools are available.

**Comment by dlcomeaux** [comment]
@matthewstern yes I found and am using that one, it seems to work fine.
