### ISSUE TITLE
How to test theme changes

### ISSUE THREAD

**Issue by MMenninger** [CMAP-REPOS/cmapplot#28]
I made some changes in a branch to the theme. Not sure how to test them. 

I changed the font and title placement. 

I made the left margin big - per CMAP standard. However I think the margin should really be x% of chart size rather than points or cm. Wecome to thoughts.

**Comment by matthewstern** [comment]
Depends what you mean by testing.

`devtools::load_all()` will load the package as it is saved locally in the branch you are working on, allowing you to test the feature you have written and see how it works. 

The file `/r/sample_graphics.r` contains a variety of pre-written ggplot code you can use to see how your features work.

`devtools::check()` will make sure you have done everything you need to do to make the package publishable--this includes documentation, correct function imports and exports, etc.

**Comment by sarahcmap** [comment]
I tried this out and after adjusting the vjust/hjust parameters and margins, I find that the plot gets pushed down - more noticeable when the title is long.  (Also have to implement left justification for multiline title, but that can come next).  Any suggestions? 
![Rplot01](https://user-images.githubusercontent.com/44509150/75179666-317b4480-5700-11ea-8700-2a850e7f3765.png)

**Comment by matthewstern** [comment]
I'm curious if the two column solution that @sarahcmap was playing with might be the trick here. The left column could contain the title and notes, and the right column could contain the legend and and plot area?

**Comment by sarahcmap** [comment]
Yeah using that approach I got here, but i did tweaking based on this specific text/example.  It needs to be generalized.  The work is in the finalizeplot branch (theme_cmap and finalize_plot R files).    

@MMenninger check out my branch when you can and let me know what you think.  Can we achieve the layout we want using just ggplot2 theme() elements as in your branch, or do we need to use the grid package as in my branch?

![Rplot02](https://user-images.githubusercontent.com/44509150/75192193-634cd500-5719-11ea-8cbc-4930115e62eb.png)

**Comment by MMenninger** [comment]
Yours looks much better. Just need to see if we can put into theme.
