### ISSUE TITLE
What are our short term goals?

### ISSUE THREAD

**Issue by MMenninger** [CMAP-REPOS/cmapplot#3]

**Comment by tallishmatt** [comment]
Hoping we can establish a firm list of these and priorities when we meet in January, but here are some ideas:

Larger scale:
- [ ] identify additional R packages that will assist in design (e.g. ggthemr) and explore best practices (e.g. bbplot from BBC)
- [ ] learn how to manipulate ggplot and additional packages to produce CMAP themed plots
   - [ ] legend location
   - [ ] title, subtitle, notes, sources, etc - font, location, appearance
   - [ ] axes - color and appearance, etc
   - [ ] CMAP colors for data
- [ ] package said theming into ggplot object(s) that can be easily called
- [ ] consider specific types of graph outputs and how ggplot can be further customized to produce 
   - [ ] CMAP race colors for race data
   - [ ] line graphs: auto-highlighting of certain years (e.g. dots and value labels on final years as in [here](https://www.cmap.illinois.gov/2050/indicators/workforce-participation#InclusiveGrowth))
   - [ ] ability to easily add recessions to charts as gray rectangles
   - [ ] ...?
- [ ] where possible build these customizations into objects or functions
- [ ] write a cookbook

**Comment by tallishmatt** [comment]
I have checked the items in the above list that I have created specific issues for. Closing this for the time being so it doesn't clutter our workflow.
