### ISSUE TITLE
conflicts and masks

### ISSUE THREAD

**Issue by matthewstern** [CMAP-REPOS/cmapplot#40]
I typically load the tidyverse library before loading cmapplot, which 'looks' great. However, I recently loaded cmapplot before tidyverse, and was surprised by the extensive list of conflicts:

![image](https://user-images.githubusercontent.com/54633946/77916245-64b07680-725e-11ea-93e6-9a8f72b9af43.png)

Why would this be? It doesn't seem to cause any issues but I am curious.

**Comment by nmpeterson** [comment]
When you load `cmapplot`, those functions from its dependencies are loaded as part of it. Nothing to worry about, as they're just being masked with identical functions from the original packages.
