### ISSUE TITLE
Package logo

### ISSUE THREAD

**Issue by nmpeterson** [CMAP-REPOS/cmapplot#62]
I spent a little bit of time working on a potential logo for the package, putting a CMAP twist on the tidyverse hexagon theme ([they're seriously obsessed](https://www.tidyverse.org)). I'm envisioning this being displayed both on the readme (i.e. GitHub project main page) like on [ggplot2](https://github.com/tidyverse/ggplot2), as well as the navigation bar for the pkgdown site.

Here's what I came up with:
![cmapplot_logo_v2](https://user-images.githubusercontent.com/4383272/95636465-d579ec00-0a54-11eb-998e-32aecbc84c99.png)

Thoughts?

**Comment by dlcomeaux** [comment]
I like the concept. What did you make this in? One idea I had that could be graphically interesting (although might be too busy...) would be to have the cmapplot text run along the white swatch in the middle, either within it or on either side. But that would require some manipulation in Illustrator, presumably.

**Comment by nmpeterson** [comment]
@dlcomeaux I currently have a 60-day trial of Photoshop on my laptop, so that's what I used. I also thought about something like what you suggested, but I was worried about text legibility at smaller sizes. The version I posted above is significantly larger than what I would want to slap on the readme.
