### ISSUE TITLE
Improvements based on comms review

### ISSUE THREAD

**Issue by matthewstern** [CMAP-REPOS/cmapplot#66]
Feel free to add/change this list based on your notes:

Fonts @nmpeterson 
- [x] Axis labels, bot not legend, should use Book
- [x] in-plot labels should use semibold
- [x] title leading should default to 1, not 0.93

Finalize @dlcomeaux 
- [x] caption default placement should be bottom
- [ ] svg outputs appear to be corrupt upon opening in illustrator
- [x] margin_legend_i should be a bit bigger
- [ ] Maybe, additional testing/exploration about the idealized web output (670 px, font sizing, etc). This may warrant some additional discussion with Ben/Joey/Dawn, but I would also recommend against going too deep here until we actually launch and people start using this. Through actual use we'll gain a better sense of what comms needs/wants

theme_cmap (@sarahcmap would you be willing to work on this?)
- [x] Add the ability to add optional axis lines that are the same thickness as grid lines (0.3 bigpts). This would utilize I think `axis.line.x` and `axis.line.y` in optional constructions that look very similar to how gridlines are currently specified.

highlight last @nmpeterson 
- [x] apply label defaults (text in semibold)
- [x] confirm that we've identified the best possible workaround for the buffer on the right side of the graph and confirm that we have clearly articulated that workaround in the documentation

recessions @matthewstern 
- [x] confirm color, alpha, and draw order settings/capabilities

colors @gritzenthaler 
- [ ] stand by on direction from Ben/Dawn

**Comment by dlcomeaux** [comment]
Note that we might need to do some additional work to add spacing between multi-line legends (vs. graphs that have two legends). See [here](https://stackoverflow.com/questions/11366964/is-there-a-way-to-change-the-spacing-between-legend-items-in-ggplot2)
