### ISSUE TITLE
Distance between axis and axis labels

### ISSUE THREAD

**Issue by dlcomeaux** [CMAP-REPOS/cmapplot#68]
As I was re-making the Census graphic, I noticed that our current default setting for the margin between axis labels and the plot is 5 big points, which is significantly larger than the similar spacing in the comms-produced graphic. Also, that value (5) is hard-coded into `theme_cmap()`, which might be better served as an adjustable value in the `overrides` list. 

Flagging here because I think this could also benefit from adding the same functionality for y-axis labels, in cases where the labels are on the side - currently, the margin for those is not manually adjusted, and remains at the default.

**Comment by matthewstern** [comment]
@dlcomeaux  Now that #72 is merged, this should be an easy fix. I support reviewing theme_cmap and theme_cmap_base for hard coded values that should move to consts.

**Comment by matthewstern** [comment]
@dlcomeaux the more I work with examples, the more I think `theme_cmap()` might want to add an arg for adding tick marks. See the manual addition [here](https://cmap-repos.github.io/cmapplot/articles/plots.html), which requires both a change to the spacing and to the ticks.

**Comment by dlcomeaux** [comment]
Hmm, yeah, that seems reasonable, and shouldn't take _too_ much work.

**Comment by matthewstern** [comment]
> 
> 
> As I was re-making the Census graphic, I noticed that our current default setting for the margin between axis labels and the plot is 5 big points, which is significantly larger than the similar spacing in the comms-produced graphic. Also, that value (5) is hard-coded into `theme_cmap()`, which might be better served as an adjustable value in the `overrides` list.
> 
> Flagging here because I think this could also benefit from adding the same functionality for y-axis labels, in cases where the labels are on the side - currently, the margin for those is not manually adjusted, and remains at the default.

@dlcomeaux can you confirm that this is still an issue? in #67 at present I see that this margin is set to `half_line / 2`:
```
    axis.text.x =        element_text(margin = margin(t = consts$half_line / 2), vjust = 1),
    axis.text.x.top =    element_text(margin = margin(b = consts$half_line / 2), vjust = 0),
    axis.text.y =        element_text(margin = margin(r = consts$half_line / 2), hjust = 1),
    axis.text.y.right =  element_text(margin = margin(l = consts$half_line / 2), hjust = 0),
```

This should make the margin 3.5 pts (14 / 2 / 2), and not hard-coded. Unless I'm missing something?

**Comment by dlcomeaux** [comment]
@matthewstern this is correct, I submitted this issue before this change to the structure of the theme, if I'm recalling correctly. Going to close this and make a new issue about adding ticks as a possible enhancement.
