### ISSUE TITLE
Improving default panel spacing

### ISSUE THREAD

**Issue by dlcomeaux** [CMAP-REPOS/cmapplot#75]
Minor change, but I think we should change the default spacing for faceted graphs (currently `unit(consts$half_line, "pt")`) to some larger value, as it can be quite tight in the current defaults, particularly when the whole background is the same color (white) and there is only a small break, which can lead to overlapping axis values.

I propose that we do this after #72 is merged.

**Comment by matthewstern** [comment]
doubled to a whole line in #67 (commit f6c1639). @dlcomeaux will you test and see if you think this should be larger?

**Comment by dlcomeaux** [comment]
> 
> 
> doubled to a whole line in #67 (commit [f6c1639](https://github.com/CMAP-REPOS/cmapplot/commit/f6c1639c84a1e6707c16689fd214b329346bbdfd)). @dlcomeaux will you test and see if you think this should be larger?

Seems fine to me. In the facet grid example, we should document how to change this if desired.
