### ISSUE TITLE
Example charts for cookbook

### ISSUE THREAD

**Issue by dlcomeaux** [CMAP-REPOS/cmapplot#78]
For the cookbook's fourth vignette, we decided to make a list of example "fully baked" CMAP charts. These should hit each of the major categories of charts that are regularly produced in CMAP publications and analyses. @gritzenthaler @nmpeterson @matthewstern @sarahcmap - please feel free to claim one (or more) of the following, or adding your own ideas, by editing this overview. 

We can also have two examples for some of these, if there are good ones - in particular, given how common line and bar charts are, those might be good to have some extra.

**Sample charts**
- [x] Line chart (a fully built-out version of the one that Matt is developing in his vignette is a good candidate for this)
- [x] A scatterplot (like [this](https://www.cmap.illinois.gov/documents/10180/1034772/PU20-0001_AGE_LABOR_FORCE_Change_in_size+copy.png/5c50d430-a633-97a8-26d9-7ffadadca080?t=1564670176836) one). Ideally, this will demonstrate changing both size and color of the points, as the linked one does.
- [x] An area chart. My current idea would be to do a variant of the Line Chart 1 above and use the transit data in a different way to do this.
- [x] Clustered bar chart: The replicated Census chart that I made should do the trick for this, as it demonstrates adjustments to bar sizes, annotations with text, dashed lines, 
- [x] Stacked bar chart (either absolute or scaled to share out of 100%)
- [x] Some kind of chart using the highlight function (and probably a bar chart). There is a census piece chart that could be modified to do this, if no one has other ideas.
- [x] A histogram
- [x] A pie chart (for example, like [these](https://www.cmap.illinois.gov/updates/all/-/asset_publisher/UIMfSLnFfMB6/content/cmap-estimates-show-improved-regional-air-quality-due-to-recent-transportation-shifts))
- [x] A faceted chart (one of the above could also accomplish this).
- [x] A chart using the race/ethnicity palette. One of the inclusive growth indicators would be a good candidate, e.g. [this](https://cmap-repos.github.io/ONTO2050-indicators/#household-income-race-ethnicity).

**Comment by matthewstern** [comment]
Thanks @dlcomeaux. In PR #79, which should hopefully be merged before we meet again in two weeks with our example code, I've established a cookbook vignette that can serve as the eventual home for these.

**Comment by nmpeterson** [comment]
I took a stab at creating the donut chart on the page @dlcomeaux linked. (Can be turned into a normal pie chart by dropping the `ylim()` call.)

Waiting for confirmation from Ben about ratio of diameters for inner/outer circles, but I think this is basically ready to go.

```r
df <- tibble(
  sector = c("Stationary energy", "Transportation", "Waste"),
  emissions = c(81.9, 34.3, 3.2)
)

p <- df %>%
  mutate(
    fraction = emissions / sum(emissions),  # Ignore if data is already a percentage
    xmax = cumsum(fraction),
    xmin = lag(xmax, default = 0)
  ) %>%
  ggplot(mapping=aes(fill=sector)) +
    geom_rect(aes(xmin = xmin, xmax = xmax,
                  ymin = 2, ymax = 3)) +
    geom_text(aes(label=sprintf("%.0f%%", fraction * 100),  # Format labels as percentage
                  x = (xmax+xmin)/2, y = 2.5),
              color = "white") +  # Change label color
    coord_polar() +
    ylim(c(0, 3)) +  # Turns a pie chart into a donut chart
    theme_cmap(gridline = "none") +  # Apply CMAP theme without gridlines
    theme(axis.text = element_blank()) +  # Turn off axis labels
    cmap_fill_discrete(palette = "community")  # Apply a CMAP color scheme

finalize_plot(p, title = "Regional emissions by sector, 2015",
              caption = "Source: Chicago Metropolitan Agency for Planning.",
              caption_valign = "top")
```

![donut](https://user-images.githubusercontent.com/4383272/98744247-ff397200-2376-11eb-8811-5f008049986e.png)

**Comment by nmpeterson** [comment]
I'm also getting very close with the scatterplot. Basically just need to improve the legend and stop the origin lines from overlapping the points if possible.

Code is part of the [same gist](https://gist.github.com/nmpeterson/e18a7cf6819d5d9b2c111aafe7d414fc) as the donut chart.

![scatter](https://user-images.githubusercontent.com/4383272/99136454-7fb3d900-25ea-11eb-8bed-ba5e24e44ea7.png)

**Comment by dlcomeaux** [comment]
[Here](https://gist.github.com/dlcomeaux/c0f50b8136351a7b39301113087f26f5) is code for the two charts below. 

The first one is a recreation of the Census chart ([here](https://www.cmap.illinois.gov/updates/all/-/asset_publisher/UIMfSLnFfMB6/content/illinois-at-risk-of-a-census-undercount-especially-in-communities-of-color)):
![clustered_bar](https://user-images.githubusercontent.com/58892984/99290848-7e5df880-2804-11eb-9096-a597e565eb9b.png)

The second is a variant of the ridership chart used as the example for `transit_ridership` in the package:
![area_chart](https://user-images.githubusercontent.com/58892984/99290673-36d76c80-2804-11eb-82c5-e86fe7cbe16d.png)

**Comment by nmpeterson** [comment]
I created a highlighted line graph using the [Gini coefficient indicator](https://www.cmap.illinois.gov/2050/indicators/income-inequality) data, which also uses `geom_text_lastonly` in a non-default manner. Code in [gist](https://gist.github.com/nmpeterson/e18a7cf6819d5d9b2c111aafe7d414fc).

![line_highlight](https://user-images.githubusercontent.com/4383272/99314295-7d3dc300-2826-11eb-8463-e7649c84bbf6.png)

**Comment by gritzenthaler** [comment]
I'll begin putting together a faceted graph and histogram, maybe even incorporate the race palette.

**Comment by nmpeterson** [comment]
@gritzenthaler I'm working on chart using the race palette right now

**Comment by nmpeterson** [comment]
Here's a stacked bar chart for the [non-SOV mode share indicator](https://www.cmap.illinois.gov/2050/indicators/non-single-occupancy-modes). Code in [gist](https://gist.github.com/nmpeterson/e18a7cf6819d5d9b2c111aafe7d414fc) (stackedbarchart.R).

![stackedbar](https://user-images.githubusercontent.com/4383272/99569703-95cceb00-2996-11eb-8ac0-43aa32e41be1.png)

**Comment by dlcomeaux** [comment]
As a heads up, I have put the charts that have already been developed into the cookbook branch.
