### ISSUE TITLE
build color palettes

### ISSUE THREAD

**Issue by matthewstern** [CMAP-REPOS/cmapplot#9]
build a range of palettes including race/eth, Chi region and peers, and various sub-palettes and color scales for discrete and continuous data. All based on the master CMAP color palette.

**Comment by nmpeterson** [comment]
This is basically resolved, as of #25 -- just waiting to hear from Nancy about discrete color palettes to replace "mobility", "prosperity", etc.

**Comment by matthewstern** [comment]
I just did some experimentation with the palettes today. When following the CMAP palette linearly, every continuous palette starts with a really light color. In many continuous palette uses, we would want a range of relatively saturated/bright  colors--say, mapping losses to gains as in this figure:

![image](https://user-images.githubusercontent.com/54633946/76027988-3eb1e380-5ef7-11ea-941c-1faed63d1516.png)

Should we just ask Nancy to build some multi-color continuous palettes as well as discrete palettes?

**Comment by nmpeterson** [comment]
I'll take a crack at a couple divergent gradients that we can run by Nancy. They will likely have to deviate from the official palette somewhat.

**Comment by matthewstern** [comment]
@gritzenthaler made a good point to me offline yesterday--eventual ideal implementation of this sort of thing may beg for not only a divergent gradient but also a way to define one color as the origin/zero color. A quick internet search suggests that this might not actually be so difficult:

https://stackoverflow.com/questions/27206798/r-assign-colors-to-values-color-gradient-palette
https://www.rdocumentation.org/packages/plotrix/versions/3.7-7/topics/color.scale

**Comment by nmpeterson** [comment]
Diverging palettes have been added in #36.

**Comment by matthewstern** [comment]
To do:
- [ ] consider streamlining naming conventions for clarity @gritzenthaler 
- [ ] consider removing `@export` tags from certain subfunctions that are allowed to be internal ([more info](https://r-pkgs.org/namespace.html#exports)) @gritzenthaler
- [ ] build a "highlight one" function that allows user to apply a highlight color to one data point in a graph, and grays to the others. consider mimicking `cmap_race_palette` functionality? See examples [here](https://www.cmap.illinois.gov/programs/regional-economic-indicators/trends#Real_Median_Household_Income). @gritzenthaler  
- [ ] consider putting the entire cmap color palette in R and making it accessible for manual scales. @matthewstern
