### ISSUE TITLE
pkgdown site graphics are Arial-only

### ISSUE THREAD

**Issue by nmpeterson** [CMAP-REPOS/cmapplot#92]
For our convenience, I set up a ["GitHub Action"](https://github.com/CMAP-REPOS/cmapplot/actions/runs/373302547/workflow) that rebuilds the pkgdown site every time a commit is pushed to master (including PR merges). This action was developed by the [r-lib team](https://github.com/r-lib/) (who developed pkgdown, devtools, usethis, roxygen2, etc.), and was set up to run the site-building functions in a virtual macOS environment operated by GitHub. (From what I can tell, a new environment is created from scratch each time the action is run, and deleted upon completion.)

The obvious issue with this, for our purposes, is that the graphics generated for our website use the non-Windows font settings (i.e. Arial-only). I think it would be possible to reconfigure the action to use a Windows environment instead (which the [R-CMD-check action](https://github.com/CMAP-REPOS/cmapplot/actions/runs/380023068/workflow) already does), if we want the graphics to use Calibri instead of Arial.

If we want the graphics to use Whitney (once we have access to it), I think the only option will be to disable the pkgdown action and rebuild the site manually from our own PCs using `pkgdown::deploy_to_branch` each time we update master. This seems like a pain in the ass, and is likely to be forgotten for minor commits. Is the trade-off worth it? What are others' thoughts on this?

**Comment by nmpeterson** [comment]
As an aside, it looks like the r-lib team is currently working on a [systemfonts](https://github.com/r-lib/systemfonts) package. I am going to keep an eye on this to see if it can make our font handling any better.

**Comment by matthewstern** [comment]
If a Windows environment is possible for the automatic pkgdown build, making that change so we can get Calibri seems worth it in the short term.

As you suggest, the question about what to do once we have access to Whitney could be moot for quite a while. One argument goes that by the time we have access, we won't be changing documentation (or the package) very often and the manual `deploy_to_branch()` might not be too terrible a lift. That being said, if we can get a Windows environment to automatically build the charts in Calibri, and we make a note on the pkgdown site to this end, maybe that is good enough.

**Comment by dlcomeaux** [comment]
My bias would be to do what requires less ongoing maintenance...so I think that the Calibri solution with some footnotes is a decent compromise.

**Comment by nmpeterson** [comment]
I wonder if I can figure out a way to create a private repository holding the font files and have those loaded into the virtual environment...

**Comment by nmpeterson** [comment]
I've created a private repo ([cmap-fonts](https://github.com/CMAP-REPOS/cmap-fonts)) and uploaded the Whitney files. I think it will be possible to reconfigure the pkgdown action to install the font files from there, and build the plots with Whitney. As part of this, I am going to attempt to make it possible for cmapplot to use Whitney on macOS, rather than switching the pkgdown action to use Windows.

**Comment by nmpeterson** [comment]
I've successfully gotten R to use Whitney on macOS. Right now, there's a bit of a hold up with implementing it for the pkgdown action, though. Since the fonts are licensed, I can only put them in a private repo, but our current billing plan doesn't allow the necessary permissions for one repo's actions to access a separate private repo. I'm talking with IT about whether we can change our billing plan.

**Comment by matthewstern** [comment]
any plans to issue a PR for Whitney use on Mac that is separate from the pkgdown build question?

**Comment by nmpeterson** [comment]
We'll be switching to a new billing plan tomorrow, which should allow us to finally get this working.

**Comment by matthewstern** [comment]
@nmpeterson it looks to me like this did not work?
 
The OSX check run on master after the merge [here](https://github.com/CMAP-REPOS/cmapplot/runs/1723605247) failed, and although the pkgdown build succeeded, the site still appears to be rendering in Arial.
