### ISSUE TITLE
Add `...` parameter to scale functions

### ISSUE THREAD

**Issue by nmpeterson** [CMAP-REPOS/cmapplot#98]
I just ran into a case where I wanted to apply a color palette to a histogram with `cmap_fill_discrete()`. I also wanted to modify the legend labels, so I added `scale_fill_discrete()` with the `labels` parameter. These two functions conflict with each other, and only the last-specified one will be applied.

```
> ggplot(FACTORS_MUNI) +
+   geom_histogram(aes(x=SCORE_OVERALL_SCALED, fill=COHORT)) +
+   theme_cmap() +
+   scale_fill_discrete(labels=c("Cohort 1", "Cohort 2", "Cohort 3", "Cohort 4")) +
+   cmap_fill_discrete(palette="community")
Scale for 'fill' is already present. Adding another scale for 'fill', which will replace
the existing scale.
```

So with the above order, I got a plot that had the cmapplot palette applied, but not my custom labels. Switching the order yields a plot with custom labels and default ggplot colors. I tried supplying the `labels` parameter to `cmap_fill_discrete`, but we have not implemented that.

My current workaround is to use `scale_fill_manual`, where I can specify my own colors and labels.

I propose that all of cmapplot's color scale functions get a `...` parameter that passes any extra parameters to the underlying ggplot scale functions that we're relying on.

**Comment by dlcomeaux** [comment]
This seems like a great addition, and I don't see any downside. It also doesn't seem like it should be too complex to implement.

**Comment by dlcomeaux** [comment]
This has been implemented.
