### ISSUE TITLE
pkgdown news page -- tie to github releases?

### ISSUE THREAD

**Issue by matthewstern** [CMAP-REPOS/cmapplot#99]
I think it would be nice to include a news page on the pkgdown site that automatically captures updates via the github releases tool. In my mind, every few PR merges should get a release update, and it would make sense to capture that in a changelog on the website.

This does not seem hard to do: https://pkgdown.r-lib.org/reference/build_news.html#yaml-config

**Comment by nmpeterson** [comment]
I support this, as a way to draw attention to new versions for the non-dev users. However, it doesn't sound quite as automatic as you're suggesting -- it's all based on a well-maintained NEWS.md file (like [pkgdown's](https://github.com/r-lib/pkgdown/blob/master/NEWS.md), which has to be written by hand as far as I can tell.

**Comment by matthewstern** [comment]
yeah, OK, it looks like I didn't quite grasp how manual the default functionality was. Still wrapping my head around this plugin as a possible solution via github action: https://intuit.github.io/auto

**Comment by nmpeterson** [comment]
@matthewstern that looks sweet!

**Comment by matthewstern** [comment]
@nmpeterson when you set up the actions for testing and pkgdown building, did you do them manually or did you get them from the "marketplace"? I'm planning to tinker with this over this coming weekend maybe, but wondering if the right way to start is installing from here: https://github.com/marketplace/actions/auto-action ?

**Comment by nmpeterson** [comment]
I configured them manually, using files in [r-lib/actions](https://github.com/r-lib/actions) as a starting point.

Be aware that with our current billing plan, we are _unable_ to use ["secrets"](https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-an-organization) at this time (which is why I haven't been able to implement the Whitney-supporting pkgdown action yet).

**Comment by matthewstern** [comment]
Per @nmpeterson, we should take a look at this: https://usethis.r-lib.org/reference/index.html#section-package-release
